autocmd BufRead,BufNewFile *.launch setfiletype roslaunch

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright

let g:ycm_global_ycm_extra_conf='~/.ycm_extra_conf.py'
let g:ycm_collect_identifiers_from_tags_files=1

if isdirectory('./include')
   set path+=./include
endif
if isdirectory('~/include')
   set path+=~/include
endif
if isdirectory('/usr/include')
   set path+=/usr/include
endif
if isdirectory('/usr/local/include')
   set path+=/usr/local/include
endif
set path+=.,**
